### ISSUE TITLE
pip install fyers-apiv3 is giving error "Building wheel for aiohttp (pyproject.toml) ... error" tried installing aiohttp, pip current version no progress could anyone provide the solution 

### ISSUE THREAD

**Issue by anilvcgithub** [Pyloris/Fryers#1]
pip install fyers-apiv3 is giving error "Building wheel for aiohttp (pyproject.toml) ... error" tried installing aiohttp, pip is on current version no progress could anyone provide me the solution  .

**Comment by Pyloris** [comment]
@anilvcgithub what version of python are you using?

**Comment by Pyloris** [comment]
you should use the beta version of aiohttp which is compatible with python3.12.
```
 pip install aiohttp==3.9.0rc0
```
Otherwise, i would suggest you downgrade your python version to python3.11.6
https://www.python.org/ftp/python/3.11.6/python-3.11.6-amd64.exe

have a look at:
https://github.com/aio-libs/aiohttp/issues/7739

**Comment by anilvcgithub** [comment]
What is this?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
